site_name: Project Style Guide

theme: 
    name: material  #readthedocs # material
    highlightjs: true  # only for readthedocs
    logo: assets/logo.svg
    favicon: assets/logo.svg
    
    
    palette:
    
        - scheme: default
          primary: black
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
        
        # Palette toggle for dark mode
        - scheme: slate
          primary: white
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
nav:
    - values.md
    - design.md
    - project-types.md
    - stages.md

extra:
  generator: false